apiVersion: v1
kind: Namespace
metadata:
  name: ss-dev
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-springboot
  namespace: ss-dev
  annotations:
    kubernetes.io/change-cause: "Release 1.1 Version"
  labels:
    app: ss
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ss
  template:
    metadata:
      labels:
        app: ss
    spec:
      #serviceAccountName: eks-sa
      automountServiceAccountToken: false
      restartPolicy: Always
      containers:
      - image: 804480554088.dkr.ecr.ap-south-1.amazonaws.com/sstest
        name: ss
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/New_York
        ports:
        - containerPort: 8080
          protocol: TCP        

---

kind: Service
apiVersion: v1
metadata:
  name: ss
  namespace: ss-dev
spec:
  type: NodePort
  selector:
    app: ss
  ports:
  - port: 8080
    protocol: TCP
